### ISSUE TITLE
文章放在二层文件夹的时候无法显示

### ISSUE THREAD

**Issue by kamingchan** [geekwen/hexo-local-admin#1]

**Comment by geekwen** [comment]
hi
目前支持的路径是这样的：
_posts、_drafts、_trash目录下所有md文件（不支持子目录）
pages的话，只支持 source/dir_name/index.md 这一种（dir_name不能以“ _ ”开头，不支持多层目录，不支持非index.md的文件）

现在功能还有限，以后慢慢扩展，感谢反馈

**Comment by onepve** [comment]
emmmm这个`以后`有点长

**Comment by geekwen** [comment]
懒癌发作一下子过去这么久了。这个月更新一个2.0的版本，到时候会解决这个问题，然后发布一些新的特性。

**Comment by onepve** [comment]
用了一星期.感觉紧缺个登陆验证.其他都还行...在搭配个腾讯cos上传.美滋滋
