### ISSUE TITLE
hexo-admin 如何支持中文？

### ISSUE THREAD

**Issue by q27488** [geekwen/hexo-local-admin#2]
你们的配置文件在哪里？ 
比如我在 _config.yml 的language: zh-CN 修改后可以支持中文。

**Comment by geekwen** [comment]
hi，目前页面上的内容很简单，单词也不多。所以暂时没有考虑做多语言。

**Comment by q27488** [comment]
好的，那另外还有个问题，用了heox-admin后，根据网上的教程： `http://www.tuicool.com/articles/umEBVfI` 图片就不能放在 source里面了，
请问如何在本地放图片呢？

**Comment by geekwen** [comment]
我博客的图片就是放在 `source/images/xxx.jpg` 下面的。这样图片生成的路径是 `/images/xxx.jpg`，所以引用的时候直接用这个路径就好了。而不是你给的链接中所说的：`/source/img/img.png`。
