### ISSUE TITLE
账号密码验证

### ISSUE THREAD

**Issue by onepve** [geekwen/hexo-local-admin#5]
可以暂时先增加一个账号密码验证才能进入后台的功能..这个急需..其他的都不是很急切

**Comment by onepve** [comment]
[比如这个](https://github.com/tajpure/hexo-editor)

**Comment by geekwen** [comment]
预计这周末会更新。这个工具定位是本地管理，账号密码这次更新不会上，后续我考虑下。

**Comment by onepve** [comment]
写博客又不是固定用一台电脑更新...我都是放腾讯服务器上写博客...电脑 和 手机写..然后自动上传到腾讯cos托管博客.美滋滋...现在是nginx反代设置的账号密码..不太方便....所以需要编辑器自带登录验证.......emmmm
